### ISSUE TITLE
Can't download pretrained model

### ISSUE THREAD

**Issue by koshian2** [MasterHow/CSFlow#2]
Hi, nice paper.

Downloading from weiyun is difficult from people living outside China. Could you please upload it somewhere else?

**Comment by MasterHow** [comment]
Thanks for the feedback. I have uploaded the resource to Baidu Cloud and released the shared link. If you have network problems, you can try this link：https://pan.baidu.com/s/1Hcj-sm5t0h6lYckOBiWjzA?pwd=6kur

**Comment by MasterHow** [comment]
I'll close this issue for now, if you need help I'll always be here. =）

**Comment by PINTO0309** [comment]
@MasterHow 
Hello. Thank you for sharing your wonderful model with us.

Unfortunately, out-of-country users have difficulty using the two URLs you kindly suggested. :crying_cat_face: Therefore, we apologize for the inconvenience, but would it be possible for you to upload the file in ZIP or tar format to the Releases tab on GitHub?

GitHub's Releases allow unlimited free uploads of up to 2 GB per file. Simply drag and drop compressed files.
https://github.com/MasterHow/CSFlow/releases

I would love to share your wonderful model with my deep learning model zoo.
https://github.com/PINTO0309/PINTO_model_zoo

Thank you in advance for your cooperation.

**Comment by MasterHow** [comment]
> @MasterHow Hello. Thank you for sharing your wonderful model with us.
> 
> Unfortunately, out-of-country users have difficulty using the two URLs you kindly suggested. 😿 Therefore, we apologize for the inconvenience, but would it be possible for you to upload the file in ZIP or tar format to the Releases tab on GitHub?
> 
> GitHub's Releases allow unlimited free uploads of up to 2 GB per file. Simply drag and drop compressed files. https://github.com/MasterHow/CSFlow/releases
> 
> I would love to share your wonderful model with my deep learning model zoo. https://github.com/PINTO0309/PINTO_model_zoo
> 
> Thank you in advance for your cooperation.

Thanks for your kindly suggestion.  In order to maintain a lightweight code repository, I decided to upload the pretrained model to Google Drive：https://drive.google.com/drive/folders/1_Fb4eLfT4bZo3g8hCX5cO28lMsDKuHvE?usp=sharing 

It's my honor to have my model added to your wonderful repository.  ; )

**Comment by PINTO0309** [comment]
@MasterHow I appreciate it very much! Thank you! :smiley:

**Comment by PINTO0309** [comment]
@MasterHow
If you know of any, please disregard. By the way, large files uploaded to the Releases tab are not counted in the file size of the main repository on GitHub. It does not affect git clone and the overall repository limit size of 1GB.

Thus, I am actively uploading 2 GB of resources daily to the Releases tab.
https://github.com/PINTO0309/openvino2tensorflow/releases
![image](https://user-images.githubusercontent.com/33194443/158503098-86bafc8c-ffb0-4292-b44f-aaa7e41313f5.png)

**Comment by MasterHow** [comment]
> @MasterHow If you know of any, please disregard. By the way, large files uploaded to the Releases tab are not counted in the file size of the main repository on GitHub. It does not affect git clone and the overall repository limit size of 1GB.
> 
> Thus, I am actively uploading 2 GB of resources daily to the Releases tab. https://github.com/PINTO0309/openvino2tensorflow/releases ![image](https://user-images.githubusercontent.com/33194443/158503098-86bafc8c-ffb0-4292-b44f-aaa7e41313f5.png)

Thanks for your advice, I have also upload the checkpoints to the Releases tab just now.

**Comment by PINTO0309** [comment]
Amazing... :smiley: 

- RAFT - ONNX 97.4MB
![image](https://user-images.githubusercontent.com/33194443/158715789-19612021-9eb9-4745-a054-2363c7731d6c.png)

- CSFlow - ONNX 22.9MB
![image](https://user-images.githubusercontent.com/33194443/158715940-7dab09cc-5d9d-414f-adce-ef5bebae9dc1.png)
